### ISSUE TITLE
cannot remove ORCID from team member

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/RSD-as-a-service#441] opened 2022-07-25 14:34 UTC
When adding a team member to a project using their full name, and then select a person from the dropdown list, the metadata is filled in (from the DOI look up, i imagine). So far so good.

However, when you later try to edit the team member, you cannot remove the DOI.
(This was necessary because i selected the wrong person)

**Comment by dmijatovic** [comment] 2022-07-26 16:03
@jiskattema I am not able to reproduce this behavior. I can remove ORCID when editing user in an project at any time. I would need more info if this error is still present.

**Comment by jiskattema** [comment] 2022-07-27 07:27
I can reproduce on Firefox (102.0 (64-bit)) on Fedora Linux; Rena can too (also Firefox).
More details:
1. edit person
2. select ORCID field
3. clear the box
4. when the last character is gone, suddenly the original ORCID is back
5. you can now press save and it is actually gone

so it seems like this is a display error in you input validation.

**Comment by dmijatovic** [comment] 2022-07-27 08:56
@jiskattema Thanks. I can reproduce it on the production version. This issue is already addressed in #428 and will be included in the next release.

**Closed by dmijatovic** 2022-07-27 08:56 UTC
